
import Navbar from '@/components/Navbar'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import CartContextProvider from '@/components/CartContext'
import { ProductContext } from '@/components/ProductContext'
import Providers from '@/components/Providers'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>

            <Toaster/>
        <ProductContext>
        <CartContextProvider>
        <div className='bg-gray-100' >
        <div className='sticky right-0  left-0 top-0 z-50'>
          <Navbar/>
        </div>
        {children}
        </div>
        </CartContextProvider>
        </ProductContext>
        </Providers>
      </body>
    </html>
  )
}
